services:
  mlprofiler_api:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - 8081:8081
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - colombus-dev_network
    volumes:
      - ../data:/mlprofiler-builder/data:rw
      - ../resources:/mlprofiler-builder/resources:rw
      - ../out:/mlprofiler-builder/out:rw
      - huggingface_cache_data:/home/standarduser/.cache/huggingface:rw
    environment:
      vLLM_INFERENCE_API_URL_PREFIX: http://vllm_inference_api:11434/v1
      VESPUCCI_PARSER_API_URL_PREFIX: http://vespucci_parser_api:1701
      VLLM_FORCE: ${VLLM_FORCE}
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY}
      LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY}
      LANGFUSE_BASE_URL: ${LANGFUSE_BASE_URL}
      LANGFUSE_FLUSH_AT: ${LANGFUSE_FLUSH_AT}
    #models:
    #  - llm_inference_api
    develop:
      watch:
        - action: sync+restart
          path: ../app
          target: /mlprofiler-builder/app
          initial_sync: true
        - action: sync
          path: ../templates
          target: /mlprofiler-builder/templates/
          initial_sync: true

  vespucci_parser_api:
    image: ghcr.io/mlprofile/fast-parsing-service:v0.1.1
    working_dir: /opt/pharo
    command: [ "--headless", "Pharo.image", "eval", "--no-quit", "Server start" ]
    ports:
      - "1701:1701"
    networks:
      - colombus-dev_network

networks:
  colombus-dev_network:
    name: colombus-dev_network

volumes:
  huggingface_cache_data:
    driver: local
