services:
  mlprofiler_api:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - 8081:8081
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - colombus-dev_network
    volumes:
      - ../data:/mlprofiler-builder/data:rw
      - ../resources:/mlprofiler-builder/resources:rw
      - ../out:/mlprofiler-builder/out:rw
      - huggingface_cache_data:/home/standarduser/.cache/huggingface:rw
    environment:
      PARSER_API_URL_PREFIX: http://ml_parser_api:1701
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY}
      LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY}
      LANGFUSE_HOST: ${LANGFUSE_HOST}
      LANGFUSE_FLUSH_AT: ${LANGFUSE_FLUSH_AT}
    models:
      - llm_inference_api
    develop:
      watch:
        - action: sync+restart
          path: ../app
          target: /mlprofiler-builder/app
          initial_sync: true
        - action: sync
          path: ../templates
          target: /mlprofiler-builder/templates/
          initial_sync: true

  ml_parser_api:
    profiles:
      - ml_parser_api
    build:
      context: ../../FAST-Parsing-Service
      dockerfile: ./dockerfile
    ports:
      - 1701:1701
    networks:
      - colombus-dev_network

networks:
  colombus-dev_network:
    external: true

volumes:
  huggingface_cache_data:
    driver: local

models:
  llm_inference_api:
    model: ai/qwen2.5:7B-Q4_0
    context_size: 4096
    runtime_flags:
      - "--threads"
      - "8"
