import os

APP_VERSION = "0.3.0"

# TODO ymu: Replace with Pydantic config
VLLM_FORCE = os.environ["VLLM_FORCE"]
if VLLM_FORCE:
    INFERENCE_API_URL_PREFIX = os.environ["vLLM_INFERENCE_API_URL_PREFIX"]
else:
    INFERENCE_API_URL_PREFIX = os.environ["LLM_INFERENCE_API_URL"]
PARSER_API_URL_PREFIX = os.environ["VESPUCCI_PARSER_API_URL_PREFIX"]
